repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key


  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.6.0'
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
