"""update-account-index

Revision ID: a7b1a867ada3
Revises: 0be96f55f50c
Create Date: 2023-07-14 16:07:36.000700

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7b1a867ada3"
down_revision = "0be96f55f50c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("account_username_key", "account", type_="unique")
    op.create_index(op.f("ix_account_username"), "account", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_username"), table_name="account")
    op.create_unique_constraint("account_username_key", "account", ["username"])
    # ### end Alembic commands ###
