"""init

Revision ID: a9857021bfe4
Revises: 
Create Date: 2023-07-14 14:19:52.909333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9857021bfe4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "username_case_sensitive_index",
        "account",
        [sa.text("upper(username)")],
        unique=True,
    )
    op.create_table(
        "books",
        sa.Column("book_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("book_id"),
    )
    op.create_index(op.f("ix_books_book_id"), "books", ["book_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_book_id"), table_name="books")
    op.drop_table("books")
    op.drop_index("username_case_sensitive_index", table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
