"""update-book-name

Revision ID: e1051675ac1d
Revises: a7b1a867ada3
Create Date: 2024-02-03 15:34:32.692223

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1051675ac1d"
down_revision = "a7b1a867ada3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("book_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("book_id"),
    )
    op.create_index(op.f("ix_book_book_id"), "book", ["book_id"], unique=False)
    op.drop_index("ix_books_book_id", table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("book_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("pages", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("book_id", name="books_pkey"),
    )
    op.create_index("ix_books_book_id", "books", ["book_id"], unique=False)
    op.drop_index(op.f("ix_book_book_id"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
