name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/app/requirements.txt

      - name: Wait for PostgreSQL to become available
        run: |
          while ! pg_isready -h localhost -p 5432 -q; do sleep 1; done

      - name: Run tests with coverage
        run: |
          export DATABASE_URL="postgresql://postgres:postgres@postgres:5432"
          coverage run -m pytest
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0

